## Creating a data form

In [2]:
import numpy as np
import pandas as pd

In [22]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

In [23]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']

df2 = pd.DataFrame(data_list, columns = columns)

In [25]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection of Column

In [31]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

## Addition of a new coloumn

In [37]:
df2["designation"] = ["Doctor", "Engineer", "Photographer", "Event Manager"]

In [38]:
df2

    Name  Age      City  Salary    designation
0   John   28  New York   65000         Doctor
1   Anna   34     Paris   70000       Engineer
2  Peter   29    Berlin   62000   Photographer
3  Linda   42    London   85000  Event Manager

## Removing Columns

In [39]:
df2.drop(["designation"], axis=1, inplace=True)

In [40]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df2.drop(["City"], axis=1)

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [44]:
df2.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [45]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selecting Rows

In [47]:
df2.loc[[1, 2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [49]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

## Selecting Subsets of Rows And Columns

In [52]:
df2.loc[[0, 1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [54]:
df2.loc[[2, 3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [55]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Conditional Selection

In [57]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [59]:
df2[(df2["Age"] > 30) & (df2['City'] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000