In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

# GroupyBy

In [9]:
cat = df.groupby('Category')['Sales'].sum()

# for i, v in cat:
#     print(i)
#     print(v)

cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [12]:
dog = df.groupby('Store')['Sales'].sum()
dog

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [14]:
wolf = df.groupby(['Category', 'Store'])['Sales'].sum()
wolf

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

# Aggregation

In [17]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [15]:
df['Sales'].mean()

np.float64(187.5)

In [16]:
df['Sales'].agg(['sum', 'mean', 'median', 'std', 'min', 'max', 'count'])

sum       1500.000000
mean       187.500000
median     190.000000
std         66.062741
min        100.000000
max        300.000000
count        8.000000
Name: Sales, dtype: float64